### ISSUE TITLE
max() error

### ISSUE THREAD

**Issue by rwiltonanl** [RomeroLab/schemarecomb#3]
Dear Romero lab,

I'm interested in trying to use schemarecomb to generate fragments for a chimeric library.   I'm using sort of a hybrid of your simple example on main github page and your tutorial example for using prealigned sequences.  I get to the following step with no apparent errors, but then get the following:

>>> best_lib = max(libraries, key=lambda x: x.mutation_rate - x.energy)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: max() arg is an empty sequence

Any advice on what I may be doing wrong would really be appreciated. 

Thank you!!

Rose

In case it would be of some help, here are the commands I'm using leading up to this:

$ python3
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import schemarecomb
/homes/xx/software/miniconda3/envs/schemarecomb/lib/python3.11/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(

>>> from Bio import SeqIO
>>> from schemarecomb import ParentSequences
>>> from schemarecomb import PDBStructure
>>> pdb_fn = '5xyz.pdb'
>>> parents_fn = 'seqs_aln.fasta'
>>> pdb = PDBStructure.from_pdb_file(pdb_fn)
>>> parents = ParentSequences.from_fasta(
... parents_fn,
... pdb_structure=pdb,
... prealigned=True
... )
>>> len(parents.records)
4
>>> parents.p0_aligned
'---MEA--Q.......'    (truncated)
>>> parents.p0_aligned ==parents.pdb_structure.renumbering_seq
True
>>> libraries = schemarecomb.generate_libraries(parents,7)

**Comment by bbremer** [comment]
Hi Rose, happy to see this package getting some use.

The `max` function will throw an error if `libraries` is empty, so it looks like the algorithm is not finding any valid libraries for the input alignment. Maybe try searching for libraries with less than 7 blocks? E.g. `libraries = schemarecomb.generate_libraries(parents, 4)`. Or the sequences may be too diverse, so that the algorithm cannot find conserved positions to place breakpoints. Playing with the [`min_block_len` and `max_block_len` parameters](https://schemarecomb.readthedocs.io/en/latest/generated/schemarecomb.generate_libraries.html#schemarecomb.generate_libraries) may also be useful.

If you think it might be a bug with the code, would you mind sharing the `seqs_aln.fasta` file? I can potentially debug if I find the time.

**Comment by rwiltonanl** [comment]
Thanks so much for your quick reply and for the advice!  I will give this a try.

Previously I had downloaded the SCHEMA software from the Arnold website, and that was working fine with these alignments and block number, so I thought I might get similar results here.  But yes, I will try to reduce the blocks and maybe take out one of the lower identity homologs.

I’d love to be able to implement the Golden gate method to generate our libraries,  and coincidentally, I think one of my colleagues recently talked to your lab about trying out some of your methods too, so we’ve got some momentum now😊

Thanks!!  I’ll let you know how it goes.

**Comment by rwiltonanl** [comment]
Hello again,

I took your suggestions and simplified the library design by removing one low homology sequence and reducing the blocks to 4.  This worked great!  It took me a few tries to figure out how to print out the results, but finally got that to work.

Thinking a little more about your response below, does the homology requirement mean that the software looks for residues that can be converted to complementary overhangs for the assembly before the actual SCHEMA libraries are generated?

If one were to use the schemarecomb to identify homologs and PDB files, is there any way to print these results out at intermediate steps?  Also, is it possible to see the schema energies or maybe get the library breakpoints so that I could calculate this with the Arnold lab software?

By the way, when I was first trying out the schemarecomb, I attempted to use your command for generating an alignment with homologs from the BLAST search.  I got a number of error messages which I pasted below.  I can easily generate my own alignments, so I’m not too concerned about this, but maybe there is an obvious mistake I’m making…

Thanks again for your help!!

Rose


>>> parents.align()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/site-packages/schemarecomb/parent_alignment.py", line 737, in align
    aln_str = web_muscle(self.records)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/site-packages/schemarecomb/parent_alignment.py", line 474, in web_muscle
    error = urlopen(url).read().decode()
            ^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/homes/rwilton/software/miniconda3/envs/schemarecomb/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request



From: Wilton, Rosemarie
Sent: Saturday, June 17, 2023 12:36 PM
To: RomeroLab/schemarecomb ***@***.***>; RomeroLab/schemarecomb ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [RomeroLab/schemarecomb] max() error (Issue #3)

Thanks so much for your quick reply and for the advice!  I will give this a try.

Previously I had downloaded the SCHEMA software from the Arnold website, and that was working fine with these alignments and block number, so I thought I might get similar results here.  But yes, I will try to reduce the blocks and maybe take out one of the lower identity homologs.

I’d love to be able to implement the Golden gate method to generate our libraries,  and coincidentally, I think one of my colleagues recently talked to your lab about trying out some of your methods too, so we’ve got some momentum now😊

Thanks!!  I’ll let you know how it goes.

**Comment by rwiltonanl** [comment]
Hello,

I came across a potential issue with my results...while trying to assemble the blocks that were generated, I realized that the BsaI cut sites don't seem to generate homologous ends.  I tried playing around with this manually and also attempted to simulate the Golden Gate assembly in SnapGene.  Is there anything I might have missed during the setup?  

Thanks!

**Comment by bbremer** [comment]
> Does the homology requirement mean that the software looks for residues that can be converted to complementary overhangs for the assembly before the actual SCHEMA libraries are generated?

Yes, the algorithm [calculates Golden-Gate-valid breakpoints](https://github.com/RomeroLab/schemarecomb/blob/8ea0a6c504566b3460b944607388be6886956fe0/src/schemarecomb/optimizers.py#L219C5-L219C5) over which blocks can be constructed. This is different from the original SCHEMA-RASPP algorithm, but it done to reduce the computational load.


> If one were to use the schemarecomb to identify homologs and PDB files, is there any way to print these results out at intermediate steps?

If I'm understanding you correctly: no, there is no external way to view the intermediate steps. If you're willing and able to do some hacking, you can add some print statements to the source code itself. For example, here's the [get_PDB() method](https://github.com/RomeroLab/schemarecomb/blob/8ea0a6c504566b3460b944607388be6886956fe0/src/schemarecomb/parent_alignment.py#L837). You could print out `pdb_srs` to see the list of PDB structures found by by the `query_blast` call. If you installed through pip, try using `import schemarecomb as sr; print(sr.__file__)` to see where the schemarecomb source files are located.


> Also, is it possible to see the schema energies or maybe get the library breakpoints so that I could calculate this with the Arnold lab software?

Each [`Library`](https://schemarecomb.readthedocs.io/en/latest/generated/schemarecomb.Library.html#schemarecomb.Library) has `breakpoints` and `energy` attributes.


> I got a number of error messages which I pasted below. 
> I realized that the BsaI cut sites don't seem to generate homologous ends.

Odd. Can you share a script (+ input files) that reproduces these errors?

**Comment by rwiltonanl** [comment]
Hello,

Sorry for my late reply…Thanks very much for your responses to my questions.  This makes sense and will help a lot as I work through learning to use this software.

Most puzzling to me at the moment is that the fragments that I generated don’t seem to have complementary ends.  I attached my input files as well as the output, and the commands I used are below.  These commands were adapted from the tutorial pages.

Thanks again for all your help.

Rose



>>> import schemarecomb
……Warning: Bio.pairwise2 has been deprecated, and we intend to remove it …..

>>> from Bio import SeqIO
>>> from schemarecomb import ParentSequences
>>> from schemarecomb import PDBStructure

>>> pdb_fn = '5zil.pdb'
>>> parents_fn = 'BR_AR2_HtdR_Fixed_aln.fasta'
>>> pdb = PDBStructure.from_pdb_file(pdb_fn)
>>> parents = ParentSequences.from_fasta(
... parents_fn,
... pdb_structure=pdb,
... prealigned=True
... )
>>> len(parents.records)
3
>>> parents.p0_aligned
'-----MQA----QITGRP….
>>> parents.p0_aligned == parents.pdb_structure.renumbering_seq
True
>>> libraries = schemarecomb.generate_libraries(parents,4)
>>> best_lib = max(libraries, key=lambda x: x.mutation_rate - x.energy)

>>> out_fn = 'bR_dna_frags.fasta'
>>> SeqIO.write(best_lib.dna_blocks, out_fn, 'fasta')
12

**Comment by bbremer** [comment]
I don't think I can see files attached to GitHub email responses. Do you mind attaching the files directly on the GitHub issue? Here's a link: https://github.com/RomeroLab/schemarecomb/issues/3. Or you email me directly at bennettjamesbremer+github@gmail.com.

**Comment by bbremer** [comment]
Thanks for emailing those files. I pushed a change that should solve the assembly issue. The output fragments from your example were able to assemble using this (admittedly very hacky) script:

```
from Bio import Seq
from Bio import SeqIO

dna_frags = [str(sr.seq) for sr in SeqIO.parse("bR_dna_frags.fasta", "fasta")]
br_frags = dna_frags[:4]


def bsai_cut(frag):
    if frag[:6] == "ggtctc":
        frag = frag[7:]

    if frag[-6:] == "gagacc":
        frag = frag[:-7]

    return frag


cut_frags = [bsai_cut(frag) for frag in br_frags]

assembly = cut_frags[0]
for frag in cut_frags[1:]:
    if assembly[-4:] == frag[:4]:
        assembly += frag[4:]
    else:
        raise ValueError

assembly_aa_seq = str(Seq.Seq(assembly).translate())

original_seqs = [str(sr.seq) for sr
                 in SeqIO.parse("BR_AR2_HtdR_Fixed_aln.fasta", "fasta")]
br_aa_seq = original_seqs[0].replace("-", "")

assert assembly_aa_seq == br_aa_seq
```

Please let me know about any other issues I can help with, or if you are able to use the tool successfully in your project!

**Comment by rwilton1** [comment]
Thanks again so much for your quick response.  I will install the update and give this a try.  I’ll try running the script below too!

Many thanks,
Rose
